In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import koreanize_matplotlib

In [62]:
year_list = []
for i in range(2008, 2019):
    year_list.append(i)
year_list

[2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]

In [63]:
file = 'avg_year_industry.csv'
#data = pd.read_csv(file, header=None)
data = pd.read_csv(file, header=None, index_col=[0])

data.columns = year_list
data

2008       2009       2010       2011       2012       2013  \
0                                                                     
A   72000.58   71999.08   71999.67   71996.25   72000.33   72001.08   
B   96001.00   96000.67   95999.25   96000.17   96000.33   96000.92   
C  575998.50  576000.83  576001.25  576002.58  575999.83  575998.92   
D   24000.17   24000.08   23999.92   23999.83   24000.17   24000.17   
E   96001.00   95999.50   96001.50   96001.67   95999.00   96000.58   
F   48000.25   48000.33   47999.42   47999.17   47999.75   47999.25   
G   72000.17   71999.83   71999.58   72000.50   72000.17   71998.58   
H   96001.17   95998.92   96001.67   95999.67   96000.08   96000.25   
I   47999.67   47999.42   47999.50   48000.08   47999.00   48000.08   
J  143998.92  143998.83  143999.17  143999.42  143998.67  143999.25   
K   72000.83   72000.67   72000.50   72000.25   71999.25   72000.33   
L   24001.00   24000.25   24000.17   23999.67   24000.67   23999.67   
N   24000.75   24000.75   23999.42   24000.33   23999.25   23999.67   

        2014       2015       2016       2017       2018  
0                                                         
A   71999.50   71999.58   72000.08   73088.08   71998.92  
B   96000.92   96001.00   95999.92  102087.58   96009.75  
C  575993.42  575999.00  576000.00  589550.25  576079.00  
D   23999.92   24000.00   24000.25   24287.17   23999.58  
E   96000.75   96001.25   96001.50   97094.33   96002.75  
F   47999.58   48000.17   48000.33   49584.25   48001.58  
G   71999.58   71999.83   72000.75   78065.83   72005.42  
H   95999.75   95999.25   96000.25  101407.42   96005.58  
I   48000.75   47999.75   48007.83   50141.00   47996.08  
J  144000.25  144000.33  144000.67  147157.75  143999.33  
K   72000.83   71999.17   71999.92   76191.17   72003.08  
L   23999.50   23999.17   24005.58   25654.17   24000.25  
N   24000.42   24000.83   24000.17   26806.50   23995.42

In [66]:
data.loc['year'] = [13.87, 13.89, 13.51, 13.27, 13.27, 13.83, 14.09, 14.36, 14.43, 13.94, 13.86]

In [68]:
result = data.T
result

0            A          B          C         D         E         F         G  \
2008  72000.58   96001.00  575998.50  24000.17  96001.00  48000.25  72000.17   
2009  71999.08   96000.67  576000.83  24000.08  95999.50  48000.33  71999.83   
2010  71999.67   95999.25  576001.25  23999.92  96001.50  47999.42  71999.58   
2011  71996.25   96000.17  576002.58  23999.83  96001.67  47999.17  72000.50   
2012  72000.33   96000.33  575999.83  24000.17  95999.00  47999.75  72000.17   
2013  72001.08   96000.92  575998.92  24000.17  96000.58  47999.25  71998.58   
2014  71999.50   96000.92  575993.42  23999.92  96000.75  47999.58  71999.58   
2015  71999.58   96001.00  575999.00  24000.00  96001.25  48000.17  71999.83   
2016  72000.08   95999.92  576000.00  24000.25  96001.50  48000.33  72000.75   
2017  73088.08  102087.58  589550.25  24287.17  97094.33  49584.25  78065.83   
2018  71998.92   96009.75  576079.00  23999.58  96002.75  48001.58  72005.42   

0             H         I          J         K         L         N   year  
2008   96001.17  47999.67  143998.92  72000.83  24001.00  24000.75  13.87  
2009   95998.92  47999.42  143998.83  72000.67  24000.25  24000.75  13.89  
2010   96001.67  47999.50  143999.17  72000.50  24000.17  23999.42  13.51  
2011   95999.67  48000.08  143999.42  72000.25  23999.67  24000.33  13.27  
2012   96000.08  47999.00  143998.67  71999.25  24000.67  23999.25  13.27  
2013   96000.25  48000.08  143999.25  72000.33  23999.67  23999.67  13.83  
2014   95999.75  48000.75  144000.25  72000.83  23999.50  24000.42  14.09  
2015   95999.25  47999.75  144000.33  71999.17  23999.17  24000.83  14.36  
2016   96000.25  48007.83  144000.67  71999.92  24005.58  24000.17  14.43  
2017  101407.42  50141.00  147157.75  76191.17  25654.17  26806.50  13.94  
2018   96005.58  47996.08  143999.33  72003.08  24000.25  23995.42  13.86

In [75]:
#공분산 결과
#cov_result = np.cov(result['A'], result['year'])

for alpha in ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']:
    print(alpha)
    insult_data = result[f'{alpha}']
    cov_result = np.corrcoef(insult_data, result['year'])
    print(cov_result)

A
[[1.         0.08203163]
 [0.08203163 1.        ]]
B
[[1.         0.08081509]
 [0.08081509 1.        ]]
C
[[1.         0.08053661]
 [0.08053661 1.        ]]
D
[[1.         0.08114407]
 [0.08114407 1.        ]]
E
[[1.         0.08141121]
 [0.08141121 1.        ]]
F
[[1.         0.08125585]
 [0.08125585 1.        ]]
G
[[1.         0.08069961]
 [0.08069961 1.        ]]
H
[[1.        0.0805822]
 [0.0805822 1.       ]]
I
[[1.         0.08281458]
 [0.08281458 1.        ]]
J
[[1.        0.0811997]
 [0.0811997 1.       ]]


In [65]:
file_2 = 'earth.csv'
e_data = pd.read_csv(file, index_col=0, header = [0, 1])
mean_tempDF = e_data.xs('평균기온(℃)', level = 1, axis = 1)
mean_tempDF['avg'] = mean_tempDF.mean(axis = 1).round(2)
avg_data = mean_tempDF['avg']
avg_data

KeyError: '평균기온(℃)'